# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-07 00:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0031_merge_20160926_2120'),
        ('wagtailcore', '0032_add_bulk_delete_page_permission'),
    ]

    operations = [
    ]
