# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-11 20:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0034_auto_20170314_1138'),
        ('wagtailcore', '0033_remove_golive_expiry_help_text'),
    ]

    operations = [
    ]
